# 管理员QQ号
admin_id:
- 1234563
- 1234564
# 指令开关（可以通过机器人调整）
command:
  ban_word: true
  ingame_key_word: true
  key_word: true
  list: true
  mc: true
  name: true
  qq: true
  shenhe: true
  whitelist: true
# 字体路径，各种数据储存路径
dict_address:
  ban_word_dict: .//config//GUGUbot//ban_word.json
  font_path: ./plugins/GUGUbot/font/MicrosoftYaHei-01.ttf
  key_word_dict: .//config//GUGUbot//key_word.json
  key_word_ingame_dict: .//config//GUGUbot//key_word_ingame.json
  shenhe_log: .//config//GUGUbot//shenhe_log.txt
  shenheman: .//config//GUGUbot//shenheman.json
  start_command_dict: .//config//GUGUbot//start_commands.json
  uuid_qqid: .//config//GUGUbot//uuid_qqid.json
  whitelist: .//server//whitelist.json
# 转发设置
forward:
  mc_to_qq: true
  qq_to_mc: true
# 服务器的IP地址，查找玩家人数的备用方案
game_ip: ''
# 服务器的端口，查找玩家人数的备用方案
game_port: ''
# 要监听，转发的qq群号
group_id:
- 1234561
- 1234562
# 绑定时同时加入白名单
whitelist_add_with_bound: false
# 退群时移除白名单
whitelist_remove_with_leave: true
