name: Sync config_default.yml

on:
  push:
    paths:
      - GUGUbot/gugubot/data/config_default.yml

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Sync config_default.yml
      run: |
        cp GUGUbot/gugubot/data/config_default.yml config_default.yml
        git config --global user.name "GUGUbot"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add config_default.yml
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Sync config_default.yml from GUGUbot/gugubot/data to root"
          git push
        fi
