name: Sync README.md

on:
  push:
    paths:
      - README.md

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Sync README.md to GUGUbot
      run: |
        cp README.md GUGUbot/README.md
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add GUGUbot/README.md
        git commit -m "Sync README.md from root to GUGUbot"
        git push
